name: random_alarm
description: An alarm app that lets you configure a list of sounds or music to wake you up.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  path_provider: ^2.0.5
  file_picker: ^4.1.0
  flutter_audio_query:
    git: https://github.com/Mayb3Nots/flutter_audio_query.git
  android_alarm_manager_plus: ^1.2.0
  audioplayers: ^0.20.1
  get: ^4.5.1
  intl: ^0.17.0
  perfect_volume_control: ^1.0.4
  slide_to_act: ^2.0.1
  wakelock: ^0.5.6
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
