name: random_alarm
description: An alarm app that lets you configure a list of sounds or music to wake you up.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^0.4.0
  flutter_mobx: ^0.3.4
  json_annotation: ^3.0.0
  path_provider: ^1.5.1
  file_picker:
    git:
      url: https://github.com/Boehrsi/plugins_flutter_file_picker.git
      ref: 192_embeddingV2
  flutter_audio_query: ^0.3.3
  android_alarm_manager: ^0.4.5+3
  audioplayers: ^0.14.0
  intl: ^0.16.1
  slide_button:
    git:
      url: https://github.com/Timoteohss/slide_button.git
      ref: master
  volume: ^0.1.4
  wakelock: ^0.1.4+1
  spotify: ^0.3.6
  flutter_dotenv: ^2.1.0
  url_launcher: ^5.4.11
  uni_links: ^0.4.0

dev_dependencies:
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.11
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/